#!/bin/bash
set -e
ROOT=.
LIB="$ROOT/lib"
STATIC="$ROOT/static"
JS="$STATIC/js"
TAGS="$ROOT/tags"
TAGJS="$JS/compiled-tags.js"

echo '[INFO] Compiling js to static dir'
rm -rf "$JS"
mkdir "$JS"
#cp -r "$LIB"/* "$JS/"
cp -r node_modules/riot/riot.min.js $JS/
riot $TAGS $TAGJS
git add "$JS"
echo '[INFO] Done compiling'
find $STATIC
