#!/bin/bash
set -e
ROOT=.
LIB="$ROOT/lib"
STATIC="$ROOT/static"
JS="$STATIC/js"
TAGS="$ROOT/tags"
TAGJS="$JS/compiled-tags.js"

echo '[INFO] Compiling js to static dir'
rm -rf "$STATIC"
mkdir -p "$JS"
cp 200.html $STATIC/
cp $LIB/* $JS/
if [ -f "node_modules/riot/riot.min.js" ]; then
  cp node_modules/riot/riot.min.js $JS/
else 
  cp $(dirname $(dirname $(which riot)))/lib/node_modules/riot/riot.min.js $JS/
fi
JSES="$(ls $JS/*.js | xargs | tr ' ' "\n" | sed "s|^$JS|<script src=\"/js|;s|$|\"></script>|" | tr -d "\n")"
echo "$JSES"
sed "s|<!--LIBFILLER-->|$JSES|" 200.html > $STATIC/200.html
riot $TAGS $TAGJS
git add "$JS"
echo '[INFO] Done compiling'
find $STATIC
